project_name_admin_homepage:
    pattern:  /ngo
    defaults: { _controller: ProjectBundleAdminBundle:Default:index }

admin_auth_login:
    pattern: /ngo/login
    defaults: { _controller: ProjectBundleAdminBundle:Auth:login}

admin_auth_signup:
    pattern: /ngo/signup
    defaults: { _controller: ProjectBundleAdminBundle:Auth:signup}
