project_core_home:
    pattern:  /
    defaults: { _controller: ProjectBundleCoreBundle:Default:index }

project_core_login:
    pattern:  /login
    defaults: { _controller: ProjectBundleCoreBundle:Auth:login }

project_core_logout:
    pattern:  /logout
    defaults: { _controller: ProjectBundleCoreBundle:Auth:logout }
